/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jboss_rhiot_beacon_lcd_MiniLcdPCD8544 */

#ifndef _Included_org_jboss_rhiot_beacon_lcd_MiniLcdPCD8544
#define _Included_org_jboss_rhiot_beacon_lcd_MiniLcdPCD8544
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jboss_rhiot_beacon_lcd_MiniLcdPCD8544
 * Method:    doInit
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_jboss_rhiot_beacon_lcd_MiniLcdPCD8544_doInit
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_jboss_rhiot_beacon_lcd_MiniLcdPCD8544
 * Method:    doClear
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jboss_rhiot_beacon_lcd_MiniLcdPCD8544_doClear
  (JNIEnv *, jobject);

/*
 * Class:     org_jboss_rhiot_beacon_lcd_MiniLcdPCD8544
 * Method:    doText
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_org_jboss_rhiot_beacon_lcd_MiniLcdPCD8544_doText
  (JNIEnv *, jobject, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
